version: '3.9'

services:

  user-db:
    image: postgres
    restart: always
    container_name: user-db
    expose:
      - "5432"
    command: -p 5432
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: postgresDB

  patient-db:
    image: postgres
    restart: always
    container_name: patient-db
    expose:
      - "5433"
    command: -p 5433
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: postgresDB

  laboratory-db:
    image: postgres
    restart: always
    container_name: laboratory-db
    expose:
      - "5434"
    command: -p 5434
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: postgresDB

  user-service:
    image: harbor.k8s.elab.rs/bolnica-2/user-service:1.1
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - user-db

  patient-service:
    image: harbor.k8s.elab.rs/bolnica-2/patient-service:1.1
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - patient-db

  laboratory-service:
    image: harbor.k8s.elab.rs/bolnica-2/laboratory-service:1.1
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - laboratory-db

  frontend:
    image: harbor.k8s.elab.rs/bolnica-2/frontend:1.1
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - laboratory-service
      - patient-service
      - user-service
